Remove -DargLine and ensure argument being set equals property to be resolved Assume the property placeholder is:
  <!-- reference to all property files -->
    <context:property-placeholder location="common.properties, servers-${env}.properties"/>

Running:
  mvn -DargLine="-Dmule.env=dev" clean test

Produces:
org.springframework.beans.factory.BeanInitializationException: Could not load properties; nested exception is java.io.FileNotFoundException: class path resource [servers-${env}.properties] cannot be opened because it does not exist

Correct command:

  ```
  mvn -Denv=dev clean test
  ```